---
- include: apt_repos.yml
  when: ansible_distribution == 'Debian'
  tags:
    - repos

- include: yum_repos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - repos

- include: apt.yml
  when: ansible_distribution == 'Debian'
  tags:
    - apt
    - pkg

- include: yum.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  tags:
    - yum
    - pkg

- include: limits.yml
  tags:
    - ulimit

- include: locales.yml
  when: ansible_distribution == 'Debian'
  tags:
    - locales

- include: profile.yml
  tags:
    - profile
